<?php
class Kwc_Abstract_List_Generator extends Kwf_Component_Generator_Table
{
    protected function _formatSelect($parentData, $select)
    {
        $select = parent::_formatSelect($parentData, $select);
        if (!$select) return $select;
        if (!Kwc_Abstract::getSetting($this->getClass(), 'hasVisible')) {
            $select->ignoreVisible(true);
        }
        if (!$parentData) {
            if (!$select->getPart(Kwf_Component_Select::IGNORE_VISIBLE)) {
                $select->whereEquals('cache_visible_parents', true);
            }
        }
        return $select;
    }

    public function getChildData($parentData, $select = array())
    {
        if (is_array($select)) $select = new Kwf_Component_Select($select);
        if (!$parentData && !$select->hasPart(Kwf_Component_Select::WHERE_CHILD_OF) && !$select->hasPart(Kwf_Component_Select::WHERE_ID)) {
            $e = new Kwf_Exception("Looking up components generated by List is slow, and must be avoided.");
            $e->logOrThrow();
        }
        $ret = parent::getChildData($parentData, $select);
        return $ret;
    }

    public function getRecursiveDataResolver()
    {
        return 'Kwc_Abstract_List_RecursiveDataResolver';
    }
}
